Support PHP 8.0
casdoor/casdoor-php-sdk pull request #25
Opened 2022-08-31 16:34 UTC by Linvery

php8.0 has some change
https://www.php.net/manual/zh/migration80.incompatible.php

2022-08-31 16:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casdoor/casdoor-php-sdk?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casdoor/casdoor-php-sdk?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casdoor/casdoor-php-sdk?pullRequest=25) it.</sub>

2022-08-31 17:13 UTC, hsluoyz requested changes

2022-08-31 17:13 UTC, hsluoyz commented on tests/OauthTest.php
> +        // $endpoint = 'http://127.0.0.1:8000';
You only changed the comments, why?

2022-08-31 18:01 UTC, Linvery commented
I accidentally deleted the removed other reviewer. I'm learning how to use the functions of GitHub and GIT.I'm sorry!

2022-09-01 02:32 UTC, hsluoyz approved these changes

2022-09-01 02:48 UTC, merged