feat: add semantic-releas
casdoor/casdoor-php-sdk pull request #27
Opened 2022-09-05 17:26 UTC by Linvery

2022-09-07 01:17 UTC, hsluoyz requested changes

2022-09-07 01:17 UTC, hsluoyz commented on package.json
> +{
Don't use Node.js. Use PHP native pipeline like: https://github.com/php-casbin/php-casbin

2022-09-07 13:40 UTC, Linvery reviewed
The dependency on package.json has been removed

2022-09-08 11:02 UTC, hsluoyz approved these changes

2022-09-08 11:02 UTC, merged