fix: can create application
casdoor/casdoor-php-sdk pull request #31
Opened 2022-09-16 17:12 UTC by Linvery

2022-09-16 17:41 UTC, hsluoyz commented
@Yamituki plz review

2022-09-17 13:59 UTC, hsluoyz requested changes

2022-09-17 13:59 UTC, hsluoyz commented on src/Auth/Application.php
> +    public array $providers = [["name" => "provider_captcha_default", "canSignUp" => false, "canSignIn" => false, "canUnlink" => false, "prompted" => false, "alertType" => "None"]];
No need for all default values

2022-09-17 13:59 UTC, hsluoyz commented on src/Auth/Application.php
>  namespace Casdoor\Auth;
Apache license header for all PHP files

2022-09-17 13:59 UTC, hsluoyz commented on tests/ApplicationTest.php
> +<?php
Apache license header for all PHP files

2022-09-17 13:59 UTC, hsluoyz commented on tests/ApplicationTest.php
> +    {
If the test us un-runnable, we usually don't add it. We can use example repo to verify it works

2022-09-19 16:24 UTC, Linvery commented on src/Auth/Application.php
> +    public array $providers = [["name" => "provider_captcha_default", "canSignUp" => false, "canSignIn" => false, "canUnlink" => false, "prompted" => false, "alertType" => "None"]];
modified

2022-09-19 17:18 UTC, hsluoyz approved these changes

2022-09-19 17:18 UTC, merged